name: FPLSA
version: "1.2.7"
license: "GPL-2.0-or-later"
date: 2025-08-29
description: |
    Finitely Presented Lie Algebras

authors:
    - name: Vladimir Gerdt
      url: http://compalg.jinr.ru/CAGroup/Gerdt/
    - name: Vladimir Kornyak
      url: http://compalg.jinr.ru/CAGroup/Kornyak

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.8"

www: https://gap-packages.github.io/FPLSA
readme: README.md
packageinfo: https://gap-packages.github.io/FPLSA/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/FPLSA/releases/download/v1.2.7/FPLSA-1.2.7.tar.gz

abstract: |
    The <span class="pkgname">FPLSA</span> package uses    the authors' C program (version 4.0) that implements    a Lie Todd-Coxeter method for converting    finitely presented Lie algebras into isomorphic    structure constant algebras.    This is called via the GAP function IsomorphismSCTableAlgebra.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Lie algebra, presentation, structure constants.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GKH25</span>]   <b class='BibAuthor'>Gerdt, V., Kornyak, V. and Horn, M.</b>,
     <i class='BibTitle'>FPLSA, Finitely Presented Lie Algebras,
             Version 1.2.7</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/FPLSA">https://gap-packages.github.io/FPLSA</a></span>.
    </p>
    

bibtex: |
    @misc{ FPLSA,
      author =           {Gerdt, V. and Kornyak, V. and Horn, M.},
      title =            {{FPLSA},  {Finitely Presented Lie Algebras}, {V}ersion
                          1.2.7},
      month =            {Aug},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/FPLSA}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{FPLSA}}},
      keywords =         {Lie algebra; presentation; structure constants},
      printedkey =       {GKH25}
    }

