name: FPLSA
version: 1.2.6
date: 2023-01-03
description: |
    Finitely Presented Lie Algebras

authors:
    - name: Vladimir Gerdt
      url: http://compalg.jinr.ru/CAGroup/Gerdt/
    - name: Vladimir Kornyak
      url: http://compalg.jinr.ru/CAGroup/Kornyak

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.8"

www: https://gap-packages.github.io/FPLSA
readme: README.md
packageinfo: https://gap-packages.github.io/FPLSA/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/FPLSA/releases/download/v1.2.6/FPLSA-1.2.6.tar.gz

abstract: |
    The <span class="pkgname">FPLSA</span> package uses    the authors' C program (version 4.0) that implements    a Lie Todd-Coxeter method for converting    finitely presented Lie algebras into isomorphic    structure constant algebras.    This is called via the GAP function IsomorphismSCTableAlgebra.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
